# Information about where the book exists on the web
repository:
  url                       : https://github.com/epapoutsellis/test_binder  # Online location of your book
  branch                    : master  # Which branch of the repository should be used when creating links (optional)
  launch_buttons: 
      notebook_interface: "jupyterlab"  # or "classic"
      colab_url: "https://colab.research.google.com"